# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  machinery:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: cd machinery && go mod download
      - run: cd machinery && go test -v ./...
      - run: cd machinery && go vet

  web:
    docker:
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - run: node --version
      - run: sudo apt-get install python
      - run: cd web && yarn
      - run: cd web && yarn test
      - run: cd web && yarn build


workflows:
  version: 2
  build:
    jobs:
      - machinery
      - web
